apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: ecomm-eureka
  ports:
    - name: eureka-service-port
      port: 8761
      targetPort: 8761
      nodePort: 31002
  type: NodePort
  